version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
    db: